import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import {
  useContractRead,
  useContractWrite,
  usePrepareContractWrite,
} from "wagmi";
import styles from "../styles/Home.module.css";
import { address, abi } from "../contract";
import { useState } from "react";

const Home: NextPage = () => {
  const [message, setMessage] = useState("");

  const { data, isError, isLoading } = useContractRead({
    address: address,
    abi,
    functionName: "getAllMeows",
    watch: true,
  });

  const { config } = usePrepareContractWrite({
    address,
    abi,
    functionName: "sayMeow",
    args: [message],
  });
  const { write } = useContractWrite(config);

  // @ts-ignore
  function submit(e) {
    e.preventDefault();
    write?.();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>title</h1>

        <p className={styles.description}>description</p>

        <form onSubmit={submit}>
          <input
            type="text"
            name="message"
            onChange={(e) => setMessage(e.target.value)}
          />

          <button>Send</button>
        </form>

        {/* @ts-ignore */}
        {data?.reverse().map((item, i) => {
          const { author, message } = item;
          return (
            <div key={i}>
              <h5>{author}</h5>
              <p>{message}</p>
            </div>
          );
        })}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
